import { Metadata } from 'next';
import Movies from '@/app/components/Movies';
import RootLayout from './layout';
import Header from '@/app/components/Header';
import Banner from '@/app/components/Banner';
import Search from '@/app/components/Search';

const API_URL = process.env.NEXT_PUBLIC_API_URL;
const API_KEY = process.env.NEXT_PUBLIC_API_KEY;

async function getMovieNow() {
  const res = await fetch(`${API_URL}/now_playing?api_key=${API_KEY}`);
  const data = await res.json();
  return data.results ? data.results[0] : null;
}

async function getAllMovies() {
  const res = await fetch(`${API_URL}/popular?api_key=${API_KEY}`);
  const data = await res.json();
  return data.results;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Home() {
  const movieNow = await getMovieNow();
  const initialMovies = await getAllMovies();

  return (
    <RootLayout>
      <Header />
      <Banner
        title={movieNow.title}
        description={movieNow.overview}
        backgroundImage={`https://image.tmdb.org/t/p/original/${movieNow.backdrop_path}`}
        vote_average={movieNow.vote_average}
      />
      <div className="flex">
        <div className="w-1/4">
          <Search />
        </div>
        <div className="w-3/4">
          <Movies initialMovies={initialMovies} />
        </div>
      </div>
    </RootLayout>
  );
}
